version: "3.8"
services:
  app:
    container_name: go-chat-tg
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - cmd/chat/.env
    environment:
      TELEGRAM_API_KEY: ${TELEGRAM_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WELCOME_MESSAGE: ${WELCOME_MESSAGE}
      AI_MODEL: ${AI_MODEL}